import type { Metadata } from "next";
import { Poppins, Source_Code_Pro } from "next/font/google";
import "@/app/styles/globals.css";
import VantaBackground from "@/components/ui/vantaBackground";
import Sidebar from "@/components/layout/sidebar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-source-code-pro",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.dots.min.js"></script>
      </head>
      <body>
        {/* vanta background effect */}
        <VantaBackground />
        {/* sidebar */}
        <Sidebar />
        <div className="ml-24">
          {children}
        </div>
      </body>
    </html>
  );
}
